wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.14
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.5
      5: 0.10.14
      8:
      - 1
      - 3
batch_size:
  desc: null
  value: 5
criterion:
  desc: null
  value: BCELoss
optimzer:
  desc: null
  value: Adam
